In [58]:
import pandas as pd
import numpy as np


In [59]:
df=pd.read_csv('financial_data.csv')
df


Sentence Sentiment
0     The GeoSolutions technology will leverage Bene...  positive
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2     For the last quarter of 2010 , Componenta 's n...  positive
3     According to the Finnish-Russian Chamber of Co...   neutral
4     The Swedish buyout firm has sold its remaining...   neutral
...                                                 ...       ...
5837  RISING costs have forced packaging producer Hu...  negative
5838  Nordic Walking was first used as a summer trai...   neutral
5839  According shipping company Viking Line , the E...   neutral
5840  In the building and home improvement trade , s...   neutral
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive

[5842 rows x 2 columns]

In [60]:
df.shape

(5842, 2)

In [61]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

nltk.download('stopwords')
all_stopwords=stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to C:\Users\Gurkirat
[nltk_data]     Singh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [62]:
sentiment_mapping = {
    'positive': 1,
    'negative': -1,
    'neutral': 0
}
df['Sentiment'] = df['Sentiment'].replace(sentiment_mapping)

In [63]:
df

Sentence  Sentiment
0     The GeoSolutions technology will leverage Bene...          1
1     $ESI on lows, down $1.50 to $2.50 BK a real po...         -1
2     For the last quarter of 2010 , Componenta 's n...          1
3     According to the Finnish-Russian Chamber of Co...          0
4     The Swedish buyout firm has sold its remaining...          0
...                                                 ...        ...
5837  RISING costs have forced packaging producer Hu...         -1
5838  Nordic Walking was first used as a summer trai...          0
5839  According shipping company Viking Line , the E...          0
5840  In the building and home improvement trade , s...          0
5841  HELSINKI AFX - KCI Konecranes said it has won ...          1

[5842 rows x 2 columns]

In [64]:
corpus=[]
for i in range(0,5842):
    review=re.sub('[^a-zA-z]',' ',df['Sentence'][i])
    review=review.lower()
    review=review.split()
    review= [ps.stem(word)for word in review if not word in set (all_stopwords)]
    review=' '.join(review)
    corpus.append(review)

    

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000)



In [66]:
X=cv.fit_transform(corpus).toarray()
y=df.iloc[:,-1].values

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.09,random_state=0)


In [68]:
from sklearn.naive_bayes import GaussianNB
classifier= GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [69]:
# Predicting the test set results
y_pred = classifier.predict(X_test)

# Evaluating the model
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Display confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Print classification report
cr = classification_report(y_test, y_pred)
print("Classification Report:")
print(cr)


Accuracy: 0.4429657794676806
Confusion Matrix:
[[ 53  15  23]
 [ 90 116  80]
 [ 57  28  64]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.27      0.58      0.36        91
           0       0.73      0.41      0.52       286
           1       0.38      0.43      0.41       149

    accuracy                           0.44       526
   macro avg       0.46      0.47      0.43       526
weighted avg       0.55      0.44      0.46       526



In [70]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the dataset
df = pd.read_csv('financial_data.csv')

# Preprocessing
ps = PorterStemmer()
nltk.download('stopwords')
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

def preprocess_text(text):
    text = re.sub('[^a-zA-Z]', ' ', text)
    text = text.lower()
    text = text.split()
    text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
    text = ' '.join(text)
    return text

df['Processed_Sentence'] = df['Sentence'].apply(preprocess_text)

# TF-IDF Vectorization
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X = tfidf_vectorizer.fit_transform(df['Processed_Sentence']).toarray()
y = df['Sentiment'].replace({'positive': 1, 'negative': -1, 'neutral': 0}).values

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train the Naive Bayes classifier
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

# Predicting the test set results
y_pred = classifier.predict(X_test)

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

cr = classification_report(y_test, y_pred)
print("Classification Report:")
print(cr)


[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


Accuracy: 0.6834901625320787
Confusion Matrix:
[[ 14 137  41]
 [  1 616  26]
 [  1 164 169]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.88      0.07      0.13       192
           0       0.67      0.96      0.79       643
           1       0.72      0.51      0.59       334

    accuracy                           0.68      1169
   macro avg       0.75      0.51      0.51      1169
weighted avg       0.72      0.68      0.63      1169

